version: "3.8"

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development

  web:
    build:
      context: .
      args:
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/v3_apuri
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    depends_on:
      - db

volumes:
  db_data:
